### ISSUE TITLE
Código de activo Fijo

### ISSUE THREAD

**Issue by rensi4rn** [kplian/sis_kactivos_fijos#11]
El alta llego a estado finalizado y no fue generado el código del activo fijo,
tampoco veo la opcion para imprimir codigo de barrar en ningun lado

![image](https://cloud.githubusercontent.com/assets/2071383/21286915/cd14214c-c436-11e6-9787-595242bad9a1.png)

**Comment by rchumacero** [comment]
En la grilla de la imagen el activo aun esta como Registrado por eso no tiene codigo. Se hace la prueba en el vps y al finalizar el alta genera el codigo normalmente

**Comment by rensi4rn** [comment]
Y como se cambia ese estado de registro, ya hice el movimiento de alta del activo fijo llego a finalizado
y no cambia ese calor, seria bueno poner un manual en la wiki de este sistema

**Comment by rensi4rn** [comment]
también este error se debe a que el estado "finalizado"   figura en archivo de restauracion como "finalización" como se ve en la captura
