### ISSUE TITLE
BUG, Transferencias devoluciones

### ISSUE THREAD

**Issue by endetde** [kplian/sis_kactivos_fijos#29]
AL hacer transferencias y devoluciones no se actualiza el responsable del activo fijo

**Comment by rensi4rn** [comment]
Aumentamos opción para considerar la finalizacion de transferencias que actualizando el funcionario responsable en la tabla activo_fijo

`-- RAC 03/03/2017
            -- aumento un if para considerar el caso de transferencias finalizadas
            -- y actulizar el responsable del activo
            -- TODO (Validaolo rodrigo)
            -- TODO que pasa cuando tranfieres de un departamento a otro ....????
            
            elsif v_movimiento.cod_movimiento = 'transf' then
                
                if v_codigo_estado_siguiente = 'finalizado' then
                    --Actualiza estado de activo fijo
                    update kaf.tactivo_fijo set
                    	en_deposito = 'no',
                    	id_funcionario = mov.id_funcionario_dest,
                    	id_persona = mov.id_persona
                     from kaf.tmovimiento_af movaf
                     inner join kaf.tmovimiento mov on mov.id_movimiento = movaf.id_movimiento
                    where kaf.tactivo_fijo.id_activo_fijo = movaf.id_activo_fijo
                    and movaf.id_movimiento = v_movimiento.id_movimiento;
                
                end if;`
