### ISSUE TITLE
BUG en reporte

### ISSUE THREAD

**Issue by endetde** [kplian/sis_kactivos_fijos#30]
Es la asignación de activo fijo

![image](https://cloud.githubusercontent.com/assets/23313650/23233116/35b41bae-f924-11e6-8eed-a6d19d9a6f27.png)

el reporte es incoherente muestras mas registros y se sale de la hoja

![image](https://cloud.githubusercontent.com/assets/23313650/23233136/4b0e8764-f924-11e6-95bf-cc97510b45a9.png)

**Comment by rensi4rn** [comment]
Se dividió la consulta para la cabecera y para el detalle,
los ítem se duplicaban por que no se consideraba que un mismo empleados puede tener diferentes cargos en su historial de la empresa, hay que considerar la fecha del reporte para determinar el cargo a usar.

Se reestructuro la apariencia del reporte en una nueva clase RMovimiento2.php

![image](https://cloud.githubusercontent.com/assets/2071383/24154687/46abf800-0e28-11e7-9db4-cf6bccd63df2.png)
