### ISSUE TITLE
Fallara WF

### ISSUE THREAD

**Issue by rensi4rn** [kplian/sis_kactivos_fijos#9]
después de que llega al estado finalizado el botón para pasar a siguiente estado sigue activo

![image](https://cloud.githubusercontent.com/assets/2071383/21286879/534b3f6c-c436-11e6-8ef3-bd897af78d17.png)

**Comment by rchumacero** [comment]
No se puede reproducir. En la prueba realizada en vps funciona bien

**Comment by rensi4rn** [comment]
![image](https://cloud.githubusercontent.com/assets/2071383/21746996/92f1e87e-d52e-11e6-9ad8-2d81f2271096.png)

**Comment by rensi4rn** [comment]
Este error es porque en wl WF el estado "finalizado"   estaba en archvio de restauracion como "finalizacion",
ya fue correjido
